# Generated by Django 4.2.21 on 2025-05-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_quiz_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Progress', 'verbose_name_plural': 'Progress'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
    ]
